ac1 to ac5
rana123bilal/netflixclone-reactjs pull request #11
Opened 2023-01-17 01:27 UTC by rana123bilal

2023-01-23 15:04 UTC, Vladlan requested changes
1. AC6 hasn't been implemented
2. Words in search input should't be reseted on search (form submit)
3. For search and sorting use query params "search?sort=genres&filter=romance"
4. AC11 hasn't been met (list should not be changed)

2023-01-23 15:04 UTC, Vladlan commented on src/components/nav-component/nav-section.js
> +import { genreListforNav } from "../../Constants.js";
Please preserve file naming consistency and make all files look the same (better to use kebab-case and not having first upper case latter)

2023-01-25 01:54 UTC, rana123bilal commented on src/components/nav-component/nav-section.js
> +import { genreListforNav } from "../../Constants.js";
changed all file names to kebab-case.

2023-01-25 01:55 UTC, rana123bilal commented
> 1. AC6 hasn't been implemented
> 2. Words in search input should't be reseted on search (form submit)
> 3. For search and sorting use query params "search?sort=genres&filter=romance"
> 4. AC11 hasn't been met (list should not be changed)

2023-01-25 01:57 UTC, rana123bilal commented on src/components/nav-component/nav-section.js
> +import { genreListforNav } from "../../Constants.js";
hello Vladislav,

I resolved all issues, but i am not sure about ac6, i think i already implemented it, because whenever i click any of the movie it changes on the top of the app and also movieId changes in the URL.

2023-01-28 08:25 UTC, Vladlan requested changes
![sr1](https://user-images.githubusercontent.com/20605638/215255612-af54a63d-d84a-42ba-8340-9e08a55da768.png)

2023-01-28 08:31 UTC, Vladlan requested changes
About ac6 - on movie click at the top movie should appear but also list of movies shoudn't change

2023-01-28 08:31 UTC, Vladlan commented on src/components/search/Search.js
> -import "./Search.css";
But you forgot to change files names

2023-01-28 08:31 UTC, Vladlan commented on src/components/nav-component/nav-section.js
> +import { genreListforNav } from "../../Constants.js";
@rana123bilal  commented below

2023-01-31 10:34 UTC, Vladlan requested changes
http://localhost:3000/search?movie=284053 is not working (I should see movie when navigating by this url in new tab)

2023-01-31 10:34 UTC, Vladlan commented on src/components/cards/card-list.js
> +        {loading && <h1 className="loading">Loading....</h1>}
Why 4 dots?

2023-01-31 10:34 UTC, Vladlan commented on src/components/home/Home.js
>  import React from "react";
File Home.js in Capital case

2023-01-31 10:34 UTC, Vladlan commented on src/components/home/Home.js
>  import React from "react";
And check please other files

2023-01-31 13:49 UTC, rana123bilal commented on src/components/home/Home.js
>  import React from "react";
changed the file names in branch..

2023-02-01 22:59 UTC, Vladlan requested changes
ACs are not met still. (
Please verify all ACs again and after verifying add the AC's description (just full copy and paste from Home task 8) to this PR description.

What I found that you are missing from the ACs:
1. Sort and filter should be able to work at the same time (e.g. I did filter and then sort)
2. Search and sort should be able to work at the same time
3. Search, filter and sort should be able to work at the same time
4. Add highlighting for filter (user should be able to see which filter has been applied)
5. From AC3 - search input value should equal to :searchQuery

My personal requirement:
When user selects movie from the bottom of the list UI should be able to programmatically scroll user to selected movie card

2024-05-07 22:41 UTC, closed without merging