add movie and delete movie functionality
rana123bilal/netflixclone-reactjs pull request #3
Opened 2022-11-20 22:04 UTC by rana123bilal

2022-11-21 11:27 UTC, Vladlan requested changes

2022-11-21 11:27 UTC, Vladlan commented on src/App.js
>          <ErrorBoundry>
ErrorBoundary should be the first component in you components tree

2022-11-21 11:27 UTC, Vladlan commented on src/components/search-component/Search.js
> +  const { setSearchedTerm } = useContext(DataContext)
Your code should not have commented code in your repo. Please remove commented code `className="output">...`

2022-11-21 11:27 UTC, Vladlan commented on src/components/cards/Card.js
> +export default function MediaCard({ id, title, image, genre, year }) {
If it is MediaCard than change file name from Card to MediaCard (also my suggestion is to have all files in kebab-case (media-card.js)

2022-11-21 11:27 UTC, Vladlan commented on src/components/cards/Card.js
> +export default function MediaCard({ id, title, image, genre, year }) {
Return prop types please

2022-11-21 11:29 UTC, Vladlan commented on src/App.js
> +  const getId = (id) => {
Why it is getId? Will this function return n id? Please find proper name for this function

2022-11-21 14:43 UTC, rana123bilal commented on src/components/cards/Card.js
> +    getId(id);
configure the eslint file.

2022-11-21 14:43 UTC, rana123bilal commented on src/components/cards/Card.js
> +export default function MediaCard({ id, title, image, genre, year }) {
made all file names to kebeb-case.

2022-11-21 14:50 UTC, rana123bilal commented on src/App.js
> +  const getId = (id) => {
changed the name of that function.

2022-11-21 15:11 UTC, Vladlan requested changes

2022-11-21 15:11 UTC, Vladlan commented on src/components/cards/Card.js
> +    getId(id);
You should add eslint in **Separate PR (pull request)** because this change will cause lots of changes not related to this PR. Also please add precommit hooks to run eslint on each commit (This was part of Module 2)

2022-11-21 15:11 UTC, Vladlan commented on src/components/nav-component/nav-section.css
> +    margin-top: -21px;
Try to not use negative margins https://blog.shimin.io/are-css-negative-margins-bad-practice/#:~:text=The%20downside%20of%20negative%20margins,This%20is%20indeed%20bad%20practice.

2022-11-21 15:11 UTC, Vladlan commented on src/components/nav-component/nav-section.js
> +      const types = {
move types to const ("SORT_TYPES") and use the instead of a string

2022-11-21 15:11 UTC, Vladlan commented on src/context/data-context.js
> +  const [openAddMovieModal, setOpenAddMovieModal] = useState(false);
openAddMovieModal is a verb. You should only use verbs for methods and functions and nouns for keys, constsants

2022-11-21 23:11 UTC, rana123bilal commented on src/components/cards/Card.js
> +    getId(id);
Noted that, add saperate PR for eslint and here is the link

https://github.com/rana123bilal/netflixclone-reactjs/pull/4

2022-11-21 23:14 UTC, rana123bilal commented on src/context/data-context.js
> +  const getMovieId = (id) => {
I changed the name of function, basically it is the setter function which set id for delete and edit.

2022-11-21 23:14 UTC, rana123bilal commented on src/components/nav-component/nav-section.css
> +    margin-top: -21px;
Negative Margins removed.

2022-11-21 23:15 UTC, rana123bilal commented on src/components/nav-component/nav-section.js
> +      const types = {
make a saperate file of Sort-types, and import it here.

2022-11-21 23:15 UTC, rana123bilal commented on src/context/data-context.js
> +  const [openAddMovieModal, setOpenAddMovieModal] = useState(false);
changed the name of this verb.

2022-11-23 18:12 UTC, Vladlan approved these changes

2022-11-23 18:35 UTC, merged