add eslint and precommit hooks
rana123bilal/netflixclone-reactjs pull request #4
Opened 2022-11-21 23:09 UTC by rana123bilal

2022-11-22 10:38 UTC, Vladlan requested changes

2022-11-22 10:38 UTC, Vladlan commented on package.json
> +  "lint-staged": {
Please configure list-staged and husky properly - it is not working.

2022-11-22 10:38 UTC, Vladlan commented on package.json
> +  "lint-staged": {
https://typicode.github.io/husky/#/

2022-11-22 10:38 UTC, Vladlan commented on package.json
> +    "lint-staged": "^13.0.3"
where is eslint?

2022-11-22 10:38 UTC, Vladlan commented on package.json
> +    "lint-staged": "^13.0.3"
When you will install eslint fix all its errors and warnings

2022-11-22 20:21 UTC, rana123bilal commented on package.json
> +  "lint-staged": {
there was an issue in the code in configuration of husky, now it is working perfectly.

2022-11-22 20:22 UTC, rana123bilal commented on package.json
> +    "lint-staged": "^13.0.3"
eslint is now installed and all fixed all errors.

2022-11-23 18:07 UTC, Vladlan requested changes

2022-11-25 15:40 UTC, closed without merging

2022-11-26 20:35 UTC, Vladlan commented
@rana123bilal please merge this branch to main