homework - 5
rana123bilal/netflixclone-reactjs pull request #5
Opened 2022-11-24 00:17 UTC by rana123bilal

Done:
- [1] - Added View Movie details feature upon clicking on any of the movie card in the list.
-  [2] - Use useState and useEffect hooks;
- [3] - Use useContext hook to avoid props drilling.

Not done:
-[1] - nothing

Final mark: 5

2022-11-26 10:40 UTC, Vladlan commented on src/components/cards/media-card.js
>      setIsHovering(false);
Why you named this fn `handleMouseOut`? It is totally clear that it is `setIsHovering`

2022-11-26 11:25 UTC, Vladlan requested changes
Also please add custom hook of any kind (it is totally up to you).

2022-11-26 11:25 UTC, Vladlan commented on src/components/movie/view-movie.js
> +  function onclickSearch() {
onclickSearch -> closeViewMovieDetails

2022-11-26 11:25 UTC, Vladlan commented on src/components/cards/media-card.js
>      setIsHovering(false);
Please correct all function names in a way:
1. Name should describe what this function is doing (not when like onClickHandler)
2. So in the end you will be able to read your JSX like `<CardMedia onClick={toggleCard}/> `

2022-11-26 11:25 UTC, Vladlan commented on src/components/cards/media-card.js
>    const handleMouseOut = () => {
setIsHovering(true) ????? Set is hovering what? maybe toggleKebabMenu(true)?

2022-11-26 11:35 UTC, Vladlan commented on src/components/cards/media-card.js
>    const handleMouseOut = () => {
Please remove setIsHovering at all and use css for this (`.class_name:hover .class {...`)

2022-11-26 11:48 UTC, Vladlan commented
Also 
1. please check again https://www.figma.com/file/fKGjrOqR6nJe6LYJopGCZ8/%5BCDP%5D-Home-Task-%E2%80%93-React-v1?node-id=0%3A1 and correct UI in view-movie.js
2. Add font according to figma
3. Check paddings in all forms (inputs)
4. Fix bug with jumping card on hover

To summarise - make UI look good (since you are a frontend engineer it should be by default)

2022-11-28 22:38 UTC, rana123bilal commented on src/components/cards/media-card.js
>      setIsHovering(false);
1 :- Removed handMouseout and handmouseOver.
2 :- Changed function names accordingly.

2022-11-28 22:44 UTC, rana123bilal commented on src/components/cards/media-card.js
> +  const cardHandler = () => {
I changed name of this function.

2022-11-28 22:44 UTC, rana123bilal commented on src/components/cards/media-card.js
> +    setViewMovieDetails,
Removed this verb.

2022-11-28 22:45 UTC, rana123bilal commented on src/components/movie/view-movie.js
> +  function onclickSearch() {
Changed.

2022-11-28 22:45 UTC, rana123bilal commented on src/components/cards/media-card.js
>    const handleMouseOut = () => {
Removed isHovering states and use Pseudo selectors instead.

2022-12-01 19:07 UTC, Vladlan approved these changes

2022-12-01 20:01 UTC, merged