Add redux and fetching data from API
rana123bilal/netflixclone-reactjs pull request #9
Opened 2022-12-09 00:57 UTC by rana123bilal

Done:
- [1] - Fetch Data with actions and passed data to components with redux.
- [2] -  All data fetches are implemented as actions and received from store by components
- [3] -  Sorting by release date and rating is implemented as redux actions
- [4] - Filtering by genre is implemented as redux actions

Not done:
nothing,

Final mark: 5

2022-12-13 22:52 UTC, Vladlan requested changes

2022-12-13 22:52 UTC, Vladlan commented on src/components/movie/Movies.css
>  }
remove commented code

2022-12-13 22:52 UTC, Vladlan commented on src/components/search/Search.js
>    const searchButtonHandler = (event) => {
searchButtonHandler -> searchMovies (or  doMoviesSearch or findMovies or smth like that)

2022-12-13 22:52 UTC, Vladlan commented on src/index.js
> -  <React.StrictMode>
Return back strict mode

2022-12-13 22:52 UTC, Vladlan commented on src/redux/actions/movie-actions.js
> +        error.message && error.response.data.message
Please check this logic and correct it `(error.message && error.response.data.message)`

2022-12-13 22:52 UTC, Vladlan commented on src/redux/reducers/movie-reducer.js
> +export const movieDetailReducer = (state = intialMovieDetailState, action) => {
`, {type, payload}`

2022-12-14 00:27 UTC, rana123bilal commented on src/redux/reducers/movie-reducer.js
> +export const movieDetailReducer = (state = intialMovieDetailState, action) => {
Hey Vladislav,
could you please explain that what do you mean by {type, payload} here?

2022-12-14 11:33 UTC, rana123bilal commented on src/components/movie/Movies.css
>  }
Commented code removed

2022-12-14 11:33 UTC, rana123bilal commented on src/components/search/Search.js
>    const searchButtonHandler = (event) => {
changed the name of function to searchMovies

2022-12-14 11:33 UTC, rana123bilal commented on src/index.js
> -  <React.StrictMode>
strict mode added

2022-12-14 11:34 UTC, rana123bilal commented on src/redux/actions/movie-actions.js
> +        error.message && error.response.data.message
now error.message logic is working perfectly

2022-12-14 12:18 UTC, Vladlan approved these changes

2022-12-14 12:26 UTC, merged